apiVersion: v1
kind: Service
metadata:
  name: tricalrevive-api
spec:
  selector:
    app: tricalrevive-api
  ports:
    - port: {{ .Values.api.servicePort }}
      targetPort: {{ .Values.api.containerPort }}
  type: LoadBalancer